//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG
    {
        public decimal ID_LOG { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<decimal> ID_LIBRO { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
    
        public virtual TBL_LIBRO TBL_LIBRO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
