//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LIBRO
    {
        public TBL_LIBRO()
        {
            this.TBL_LOG = new HashSet<TBL_LOG>();
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
    
        public decimal ID_LIBRO { get; set; }
        public string NOMBRE_LIBRO { get; set; }
        public string NOMBRE_AUTOR { get; set; }
    
        public virtual ICollection<TBL_LOG> TBL_LOG { get; set; }
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
